FROM node:18-alpine3.14

RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache g++
RUN apk add --no-cache gcc musl-dev python3-dev

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm

RUN mkdir /app
WORKDIR /app

COPY package*.json ./

RUN pnpm install

COPY . .

EXPOSE 8000

CMD [ "gunicorn", "-k", "eventlet", "-w 1", "--reload", "app:app", "-b","0.0.0.0:8000" ]
